<?php

/**
 * Implementation of hook_menu().
 */
function ciandt_wechat_vocation_menu() {
  $items = array();
  $items['admin/config/vocation/enterprise-wechat'] = array(
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ciandt_wechat_vocation_enterprise_wechat_settings'),
    'title' => 'Enterprise Wechat Settings',
    'description' => 'Set access keys and other necessary configurations for enterprise wechat.',
  );
  
  $items['webchat_callback'] = array(
    'title' => 'CI&T vocation management system',
    'page callback' => 'ciandt_wechat_vocation_callback',
    'access arguments' => array('access content')
  );

  return $items;
}


function ciandt_wechat_vocation_callback(){

}

/**
 * Menu callback to configure module settings.
 */
function ciandt_wechat_vocation_enterprise_wechat_settings($form, &$form_state){
  $form['enterprise_wechat_corp_id'] = array(
    '#type' => 'textfield', 
    '#title' => t('CorpID'), 
    '#size' => 60, 
    '#maxlength' => 128, 
    '#required' => TRUE,
    '#default_value' => variable_get('enterprise_wechat_corp_id'),
    '#description' => t('Set the enterprise wechat CorpID.'),
  );
  
  $form['enterprise_wechat_secret'] = array(
    '#type' => 'textfield', 
    '#title' => t('Secret'), 
    '#size' => 60, 
    '#maxlength' => 128, 
    '#required' => TRUE,
    '#default_value' => variable_get('enterprise_wechat_secret'),
    '#description' => t('Set the enterprise wechat Secret.'),
  );
  
  $form['enterprise_wechat_dev_mode_token'] = array(
    '#type' => 'textfield', 
    '#title' => t('Dev mode Token'), 
    '#size' => 60, 
    '#maxlength' => 128, 
    '#required' => TRUE,
    '#default_value' => variable_get('enterprise_wechat_dev_mode_token'),
    '#description' => t('Set the token for dev mode.'),
  );
  
  $form['enterprise_wechat_dev_mode_encoding_aes_key'] = array(
    '#type' => 'textfield', 
    '#title' => t('Dev mode EncodingAESKey'), 
    '#size' => 60, 
    '#maxlength' => 128, 
    '#required' => TRUE,
    '#default_value' => variable_get('enterprise_wechat_dev_mode_encoding_aes_key'),
    '#description' => t('Set the EncodingAESKey for dev mode.'),
  );
  
  $form['vacation_approver_wechat_tag_name'] = array(
    '#type' => 'textfield', 
    '#title' => t('Approval Wechat Tag Name'), 
    '#size' => 60, 
    '#maxlength' => 128, 
    '#required' => TRUE,
    '#default_value' => variable_get('vacation_approver_wechat_tag_name'),
    '#description' => t('Set the Wechat tag name for approvers.'),
  );
  
  return system_settings_form($form);  
}

/**
 * Rules action for push notification.
 */
function ciandt_wechat_vocation_push_wechat_notification($target, $message) {

  // TODO: Get wechat uid/token_id by $target.

  // TODO: Send message with wechat api.

  drupal_set_message(t("Vocation approve notification has been sent to approver"));
  return TRUE;
}
